### ISSUE TITLE
Sudden change in the size of all gifs .

### ISSUE THREAD

**Issue by VardaanAggarwal** [TheDudeThatCode/TheDudeThatCode#3]
Hey @TheDudeThatCode, I want to bring your attention to this issue of sudden and strange enlargening of all the assets that are available to your repo.
Can you please fix this issue or something, and please let know of the issue that has occurred to cause this problem .

**Comment by mostafakamar2308** [comment]
it is propably due to using units (px) in the syntax like `<img src="whatever" width="100px">`
instead, removing the unit (px) fixed the issue for me
So this works now for me `<img src="whatever" width="100">`

**Comment by TheDudeThatCode** [comment]
This issue is fixed, hence closing!!
